#!/usr/bin/env bash
# 由 mapping.json 生成（主 agent 重生成于 2026-09-20，已含 port-* → docs/runbooks/ 的裁决纠正）
# 用法: cd /home/CNS2026495165/dsh && bash .workspace/docs-reorg/tools/move_commands.sh
# 幂等：源不存在时跳过（便于中断后续跑）
set -u
cd "$(git rev-parse --show-toplevel)" || exit 2
ok=0; skip=0; fail=0
do_move() { # $1=cmd $2=from $3=to
  if [ ! -e "$2" ]; then echo "SKIP(源不存在) $2"; skip=$((skip+1)); return 0; fi
  mkdir -p "$(dirname "$3")"
  if $1 "$2" "$3" 2>/dev/null; then echo "OK   $2 -> $3"; ok=$((ok+1));
  else echo "FAIL $2 -> $3"; fail=$((fail+1)); fi
}

# ── ① 根级文档（24 条 git mv）──
do_move "git mv" "audit-btw.md" ".workspace/reports/audits/btw/audit-btw.md"
do_move "git mv" "audit-btw-model.md" ".workspace/reports/audits/btw/audit-btw-model.md"
do_move "git mv" "audit-btw-subagent.md" ".workspace/reports/audits/btw/audit-btw-subagent.md"
do_move "git mv" "audit-subagent-arch-A.md" ".workspace/reports/audits/subagent/audit-subagent-arch-A.md"
do_move "git mv" "audit-subagent-arch-B.md" ".workspace/reports/audits/subagent/audit-subagent-arch-B.md"
do_move "git mv" "audit-wallpaper.md" ".workspace/reports/audits/wallpaper/audit-wallpaper.md"
do_move "git mv" "audit-upstream-upgrade.md" ".workspace/reports/audits/upstream/audit-upstream-upgrade.md"
do_move "git mv" "audit-local-customizations.md" ".workspace/reports/audits/machine/audit-local-customizations.md"
do_move "git mv" "execute-btw.md" ".workspace/reports/execs/btw/execute-btw.md"
do_move "git mv" "execution-btw-model.md" ".workspace/reports/execs/btw/execution-btw-model.md"
do_move "git mv" "execute-wallpaper.md" ".workspace/reports/execs/wallpaper/execute-wallpaper.md"
do_move "git mv" "review-btw.md" ".workspace/reports/execs/btw/review-btw.md"
do_move "git mv" "review-wallpaper.md" ".workspace/reports/execs/wallpaper/review-wallpaper.md"
do_move "git mv" "execution-2b.md" ".workspace/reports/execs/subagent/execution-2b.md"
do_move "git mv" "execution-subagent-tokps.md" ".workspace/reports/execs/subagent/execution-subagent-tokps.md"
do_move "git mv" "btw-wallpaper-plan.md" ".workspace/reports/plans/btw-wallpaper-plan.md"
do_move "git mv" "wiring-plan.md" ".workspace/reports/plans/wiring-plan.md"
do_move "git mv" "local-api-surface.md" ".workspace/reports/reference/local-api-surface.md"
do_move "git mv" "switch-web2-runbook.md" "docs/runbooks/switch-web2-runbook.md"
do_move "git mv" "verify-runbook.md" "docs/runbooks/verify-runbook.md"
do_move "git mv" "port-taste.md" "docs/runbooks/port-taste.md"
do_move "git mv" "port-tokps-web2.md" "docs/runbooks/port-tokps-web2.md"
do_move "git mv" "port-vision-adam.md" "docs/runbooks/port-vision-adam.md"
do_move "git mv" "port-wallpaper.md" "docs/runbooks/port-wallpaper.md"

# ── ② .workspace 已跟踪条目（161 条 git mv）──
do_move "git mv" ".workspace/acceptance-exec.md" ".workspace/reports/execs/acceptance/acceptance-exec.md"
do_move "git mv" ".workspace/RESTART-ACCEPTANCE.md" ".workspace/reports/execs/acceptance/RESTART-ACCEPTANCE.md"
do_move "git mv" ".workspace/audit-a-lagfix.md" ".workspace/reports/audits/lagfix/audit-a-lagfix.md"
do_move "git mv" ".workspace/audit-b-btw.md" ".workspace/reports/audits/btw/audit-b-btw.md"
do_move "git mv" ".workspace/audit-c-usage-vision.md" ".workspace/reports/audits/usage-vision/audit-c-usage-vision.md"
do_move "git mv" ".workspace/audit-d-plugins.md" ".workspace/reports/audits/plugins/audit-d-plugins.md"
do_move "git mv" ".workspace/borrow-015-exec.md" ".workspace/reports/execs/borrow-015/borrow-015-exec.md"
do_move "git mv" ".workspace/borrow-015-groupA-exec.md" ".workspace/reports/execs/borrow-015/borrow-015-groupA-exec.md"
do_move "git mv" ".workspace/borrow-015-groupB-exec.md" ".workspace/reports/execs/borrow-015/borrow-015-groupB-exec.md"
do_move "git mv" ".workspace/borrow-015-groupC-exec.md" ".workspace/reports/execs/borrow-015/borrow-015-groupC-exec.md"
do_move "git mv" ".workspace/btw-image-pipeline-audit.md" ".workspace/reports/audits/btw/btw-image-pipeline-audit.md"
do_move "git mv" ".workspace/btw-live-stream-audit.md" ".workspace/reports/audits/btw/btw-live-stream-audit.md"
do_move "git mv" ".workspace/btw-model-v41-exec.md" ".workspace/reports/execs/btw/btw-model-v41-exec.md"
do_move "git mv" ".workspace/btw-open-p0-diagnosis.md" ".workspace/reports/diagnostics/btw/btw-open-p0-diagnosis.md"
do_move "git mv" ".workspace/btw-p0-exec.md" ".workspace/reports/execs/btw/btw-p0-exec.md"
do_move "git mv" ".workspace/btw-request-images-explained.md" ".workspace/reports/reference/btw-request-images-explained.md"
do_move "git mv" ".workspace/btw-ui-batch-exec.md" ".workspace/reports/execs/btw/btw-ui-batch-exec.md"
do_move "git mv" ".workspace/btw-ui-exec.md" ".workspace/reports/execs/btw/btw-ui-exec.md"
do_move "git mv" ".workspace/btw-ui-gap-audit.md" ".workspace/reports/audits/btw/btw-ui-gap-audit.md"
do_move "git mv" ".workspace/btw-upgrade-audit.md" ".workspace/reports/audits/btw/btw-upgrade-audit.md"
do_move "git mv" ".workspace/btw-upgrade-impl-audit.md" ".workspace/reports/audits/btw/btw-upgrade-impl-audit.md"
do_move "git mv" ".workspace/btw-upgrade-impl-exec.md" ".workspace/reports/execs/btw/btw-upgrade-impl-exec.md"
do_move "git mv" ".workspace/btw-upgrade-impl-exec-patches.md" ".workspace/reports/execs/btw/btw-upgrade-impl-exec-patches.md"
do_move "git mv" ".workspace/btw-upgrade-plan.md" ".workspace/reports/plans/btw/btw-upgrade-plan.md"
do_move "git mv" ".workspace/btw-usage-ui-audit.md" ".workspace/reports/audits/btw/btw-usage-ui-audit.md"
do_move "git mv" ".workspace/btw-v2-runbook.md" ".workspace/reports/runbooks/btw-v2-runbook.md"
do_move "git mv" ".workspace/combined-restore-runbook.md" ".workspace/reports/runbooks/combined-restore-runbook.md"
do_move "git mv" ".workspace/distributed-control-exec.md" ".workspace/reports/execs/distributed/distributed-control-exec.md"
do_move "git mv" ".workspace/doc-restructure-exec.md" ".workspace/reports/execs/docs/doc-restructure-exec.md"
do_move "git mv" ".workspace/dsh-workerspace-research.md" ".workspace/reports/research/dsh-workerspace-research.md"
do_move "git mv" ".workspace/final-audit-a-patches.md" ".workspace/reports/audits/final/final-audit-a-patches.md"
do_move "git mv" ".workspace/final-audit-b-plugins.md" ".workspace/reports/audits/final/final-audit-b-plugins.md"
do_move "git mv" ".workspace/final-audit-c-config.md" ".workspace/reports/audits/final/final-audit-c-config.md"
do_move "git mv" ".workspace/final-audit-d-distributed.md" ".workspace/reports/audits/final/final-audit-d-distributed.md"
do_move "git mv" ".workspace/glm53-flash-image-smoke.md" ".workspace/reports/research/glm53-flash-image-smoke.md"
do_move "git mv" ".workspace/goal-p0a-exec.md" ".workspace/reports/execs/goal/goal-p0a-exec.md"
do_move "git mv" ".workspace/goal-pending-subagent-exec.md" ".workspace/reports/execs/goal/goal-pending-subagent-exec.md"
do_move "git mv" ".workspace/goal-round-gap-audit.md" ".workspace/reports/audits/goal/goal-round-gap-audit.md"
do_move "git mv" ".workspace/hotreload-a-loader.md" ".workspace/reports/research/hotreload/hotreload-a-loader.md"
do_move "git mv" ".workspace/hotreload-b-inventory.md" ".workspace/reports/research/hotreload/hotreload-b-inventory.md"
do_move "git mv" ".workspace/hotreload-c-upstream.md" ".workspace/reports/research/hotreload/hotreload-c-upstream.md"
do_move "git mv" ".workspace/hotreload-e-design.md" ".workspace/reports/research/hotreload/hotreload-e-design.md"
do_move "git mv" ".workspace/incident-piai-model-selection.md" ".workspace/reports/incidents/incident-piai-model-selection.md"
do_move "git mv" ".workspace/lag-audit-diff.md" ".workspace/reports/audits/lagfix/lag-audit-diff.md"
do_move "git mv" ".workspace/lag-audit-mechanism.md" ".workspace/reports/audits/lagfix/lag-audit-mechanism.md"
do_move "git mv" ".workspace/lag-fix-audit.md" ".workspace/reports/audits/lagfix/lag-fix-audit.md"
do_move "git mv" ".workspace/lag-fix-exec.md" ".workspace/reports/execs/lagfix/lag-fix-exec.md"
do_move "git mv" ".workspace/lag-fix-guard.md" ".workspace/reports/execs/lagfix/lag-fix-guard.md"
do_move "git mv" ".workspace/lag-fix-runbook.md" ".workspace/reports/runbooks/lag-fix-runbook.md"
do_move "git mv" ".workspace/lowrisk-fix-exec.md" ".workspace/reports/execs/lagfix/lowrisk-fix-exec.md"
do_move "git mv" ".workspace/master-runbook.md" ".workspace/reports/runbooks/master-runbook.md"
do_move "git mv" ".workspace/opencode-deepseek-v4-flash-probe.md" ".workspace/reports/research/opencode-deepseek-v4-flash-probe.md"
do_move "git mv" ".workspace/p0a-patch-hmr-exec.md" ".workspace/reports/execs/p0-hotload/p0a-patch-hmr-exec.md"
do_move "git mv" ".workspace/p0b-settings-switch-exec.md" ".workspace/reports/execs/p0-hotload/p0b-settings-switch-exec.md"
do_move "git mv" ".workspace/p0c-restart-helper-exec.md" ".workspace/reports/execs/p0-hotload/p0c-restart-helper-exec.md"
do_move "git mv" ".workspace/p1-hotswap-gate-exec.md" ".workspace/reports/execs/p0-hotload/p1-hotswap-gate-exec.md"
do_move "git mv" ".workspace/pptmaster-exec.md" ".workspace/reports/execs/pptmaster/pptmaster-exec.md"
do_move "git mv" ".workspace/pptmaster-research.md" ".workspace/reports/research/pptmaster/pptmaster-research.md"
do_move "git mv" ".workspace/pptmaster-skill-research.md" ".workspace/reports/research/pptmaster/pptmaster-skill-research.md"
do_move "git mv" ".workspace/slot-mod-audit.md" ".workspace/reports/audits/slots/slot-mod-audit.md"
do_move "git mv" ".workspace/ssh-gui-audit.md" ".workspace/reports/audits/ssh-gui/ssh-gui-audit.md"
do_move "git mv" ".workspace/ssh-gui-exec.md" ".workspace/reports/execs/ssh-gui/ssh-gui-exec.md"
do_move "git mv" ".workspace/subagent-model-gui-audit.md" ".workspace/reports/audits/subagent-model/subagent-model-gui-audit.md"
do_move "git mv" ".workspace/subagent-model-settings-exec.md" ".workspace/reports/execs/subagent-model/subagent-model-settings-exec.md"
do_move "git mv" ".workspace/upstream-015-diff.md" ".workspace/reports/audits/upstream/upstream-015-diff.md"
do_move "git mv" ".workspace/upstream-borrow-validation.md" ".workspace/reports/audits/upstream/upstream-borrow-validation.md"
do_move "git mv" ".workspace/usage-chart-audit.md" ".workspace/reports/audits/usage/usage-chart-audit.md"
do_move "git mv" ".workspace/usage-chart-restart-acceptance.md" ".workspace/reports/execs/acceptance/usage-chart-restart-acceptance.md"
do_move "git mv" ".workspace/usage-heatmap-exec.md" ".workspace/reports/execs/usage/usage-heatmap-exec.md"
do_move "git mv" ".workspace/usage-tooltip-exec.md" ".workspace/reports/execs/usage/usage-tooltip-exec.md"
do_move "git mv" ".workspace/vision-exp-probe.md" ".workspace/reports/research/vision/vision-exp-probe.md"
do_move "git mv" ".workspace/vision-flash-test.md" ".workspace/reports/research/vision/vision-flash-test.md"
do_move "git mv" ".workspace/vision-prompt-exec.md" ".workspace/reports/execs/vision/vision-prompt-exec.md"
do_move "git mv" ".workspace/vision-settings-capability-exec.md" ".workspace/reports/execs/vision/vision-settings-capability-exec.md"
do_move "git mv" ".workspace/workerspace-exec.md" ".workspace/reports/execs/workerspace/workerspace-exec.md"
do_move "git mv" ".workspace/workspace-plugins-deep-research.md" ".workspace/reports/research/workspace-plugins-deep-research.md"
do_move "git mv" ".workspace/NEXT_SESSION_PROMPT.txt" ".workspace/reports/handoff/NEXT_SESSION_PROMPT.txt"
do_move "git mv" ".workspace/push-log.txt" ".workspace/reports/push-logs/push-log.txt"
do_move "git mv" ".workspace/push-log2.txt" ".workspace/reports/push-logs/push-log2.txt"
do_move "git mv" ".workspace/glm53_image.json" ".workspace/probes/captures/glm53_image.json"
do_move "git mv" ".workspace/glm53_text.json" ".workspace/probes/captures/glm53_text.json"
do_move "git mv" ".workspace/models_fresh.json" ".workspace/probes/captures/models_fresh.json"
do_move "git mv" ".workspace/models_list.json" ".workspace/probes/captures/models_list.json"
do_move "git mv" ".workspace/oc_models.json" ".workspace/probes/captures/oc_models.json"
do_move "git mv" ".workspace/oc_models_v41_probe.json" ".workspace/probes/captures/oc_models_v41_probe.json"
do_move "git mv" ".workspace/oc_req_v41_image.json" ".workspace/probes/captures/oc_req_v41_image.json"
do_move "git mv" ".workspace/oc_req_v41_text.json" ".workspace/probes/captures/oc_req_v41_text.json"
do_move "git mv" ".workspace/oc_req_vexp2_image.json" ".workspace/probes/captures/oc_req_vexp2_image.json"
do_move "git mv" ".workspace/oc_req_vexp_image.json" ".workspace/probes/captures/oc_req_vexp_image.json"
do_move "git mv" ".workspace/oc_req_vexp_text.json" ".workspace/probes/captures/oc_req_vexp_text.json"
do_move "git mv" ".workspace/oc_resp_v41_image.json" ".workspace/probes/captures/oc_resp_v41_image.json"
do_move "git mv" ".workspace/oc_resp_v41_text.json" ".workspace/probes/captures/oc_resp_v41_text.json"
do_move "git mv" ".workspace/oc_resp_vexp2_image.json" ".workspace/probes/captures/oc_resp_vexp2_image.json"
do_move "git mv" ".workspace/oc_resp_vexp_image.json" ".workspace/probes/captures/oc_resp_vexp_image.json"
do_move "git mv" ".workspace/oc_resp_vexp_text.json" ".workspace/probes/captures/oc_resp_vexp_text.json"
do_move "git mv" ".workspace/req1_image.json" ".workspace/probes/captures/req1_image.json"
do_move "git mv" ".workspace/req1b_bigbudget.json" ".workspace/probes/captures/req1b_bigbudget.json"
do_move "git mv" ".workspace/req2_text.json" ".workspace/probes/captures/req2_text.json"
do_move "git mv" ".workspace/req_a_rawb64.json" ".workspace/probes/captures/req_a_rawb64.json"
do_move "git mv" ".workspace/req_b_image.json" ".workspace/probes/captures/req_b_image.json"
do_move "git mv" ".workspace/req_gem_ctrl.json" ".workspace/probes/captures/req_gem_ctrl.json"
do_move "git mv" ".workspace/req_vexp_ctrl.json" ".workspace/probes/captures/req_vexp_ctrl.json"
do_move "git mv" ".workspace/req_vexp_image.json" ".workspace/probes/captures/req_vexp_image.json"
do_move "git mv" ".workspace/req_vexp_text.json" ".workspace/probes/captures/req_vexp_text.json"
do_move "git mv" ".workspace/resp1_raw.json" ".workspace/probes/captures/resp1_raw.json"
do_move "git mv" ".workspace/resp1b.json" ".workspace/probes/captures/resp1b.json"
do_move "git mv" ".workspace/resp2_raw.json" ".workspace/probes/captures/resp2_raw.json"
do_move "git mv" ".workspace/resp_a.json" ".workspace/probes/captures/resp_a.json"
do_move "git mv" ".workspace/resp_b.json" ".workspace/probes/captures/resp_b.json"
do_move "git mv" ".workspace/resp_gem_ctrl.json" ".workspace/probes/captures/resp_gem_ctrl.json"
do_move "git mv" ".workspace/resp_vexp_ctrl.json" ".workspace/probes/captures/resp_vexp_ctrl.json"
do_move "git mv" ".workspace/resp_vexp_image.json" ".workspace/probes/captures/resp_vexp_image.json"
do_move "git mv" ".workspace/resp_vexp_text.json" ".workspace/probes/captures/resp_vexp_text.json"
do_move "git mv" ".workspace/v4f-test.png" ".workspace/probes/captures/v4f-test.png"
do_move "git mv" ".workspace/settings-after-fix.json" ".workspace/probes/settings-snapshots/settings-after-fix.json"
do_move "git mv" ".workspace/settings-fixed-test.json" ".workspace/probes/settings-snapshots/settings-fixed-test.json"
do_move "git mv" ".workspace/settings-live-check.json" ".workspace/probes/settings-snapshots/settings-live-check.json"
do_move "git mv" ".workspace/settings-live-final.json" ".workspace/probes/settings-snapshots/settings-live-final.json"
do_move "git mv" ".workspace/settings-sim-final.json" ".workspace/probes/settings-snapshots/settings-sim-final.json"
do_move "git mv" ".workspace/settings-sim-new.json" ".workspace/probes/settings-snapshots/settings-sim-new.json"
do_move "git mv" ".workspace/settings-sim-old.json" ".workspace/probes/settings-snapshots/settings-sim-old.json"
do_move "git mv" ".workspace/settings-snapshot.json" ".workspace/probes/settings-snapshots/settings-snapshot.json"
do_move "git mv" ".workspace/btw-wf-v2.cjs" ".workspace/probes/workflow-drivers/btw-wf-v2.cjs"
do_move "git mv" ".workspace/btw-wf-v2.mjs" ".workspace/probes/workflow-drivers/btw-wf-v2.mjs"
do_move "git mv" ".workspace/lag-fix-wf.mjs" ".workspace/probes/workflow-drivers/lag-fix-wf.mjs"
do_move "git mv" ".workspace/workflow-2phase-template.mjs" ".workspace/probes/workflow-drivers/workflow-2phase-template.mjs"
do_move "git mv" ".workspace/diag-piai-route.mjs" ".workspace/probes/workflow-drivers/diag-piai-route.mjs"
do_move "git mv" ".workspace/diag-settings-config.mjs" ".workspace/probes/workflow-drivers/diag-settings-config.mjs"
do_move "git mv" ".workspace/.review-tmp" ".workspace/probes/legacy/review-tmp"
do_move "git mv" ".workspace/.tmp-boot3080.html" ".workspace/probes/legacy/tmp-boot3080.html"
do_move "git mv" ".workspace/.tmp-boot3080-plugin-restore.html" ".workspace/probes/legacy/tmp-boot3080-plugin-restore.html"
do_move "git mv" ".workspace/.tmp-cordis.js" ".workspace/probes/legacy/tmp-cordis.js"
do_move "git mv" ".workspace/.tmp-inventory.js" ".workspace/probes/legacy/tmp-inventory.js"
do_move "git mv" ".workspace/dsh-index.html" ".workspace/probes/legacy/dsh-index.html"
do_move "git mv" ".workspace/acceptance-probe" ".workspace/probes/acceptance"
do_move "git mv" ".workspace/mmt-probe" ".workspace/probes/mmt"
do_move "git mv" ".workspace/heat-check" ".workspace/probes/heat-check"
do_move "git mv" ".workspace/p1-hotswap-lab" ".workspace/probes/hotswap-lab"
do_move "git mv" ".workspace/btw-ui-previews" ".workspace/probes/previews/btw-ui"
do_move "git mv" ".workspace/usage-tooltip-previews" ".workspace/probes/previews/usage-tooltip"
do_move "git mv" ".workspace/deploy" ".workspace/workstreams/deploy/deploy"
do_move "git mv" ".workspace/deploy-015" ".workspace/workstreams/deploy/deploy-015"
do_move "git mv" ".workspace/deploy-lag" ".workspace/workstreams/deploy/deploy-lag"
do_move "git mv" ".workspace/deploy-p0" ".workspace/workstreams/deploy/deploy-p0"
do_move "git mv" ".workspace/deploy-pptmaster" ".workspace/workstreams/deploy/deploy-pptmaster"
do_move "git mv" ".workspace/deploy-slots" ".workspace/workstreams/deploy/deploy-slots"
do_move "git mv" ".workspace/deploy-ssh-gui" ".workspace/workstreams/deploy/deploy-ssh-gui"
do_move "git mv" ".workspace/deploy-subagent-model" ".workspace/workstreams/deploy/deploy-subagent-model"
do_move "git mv" ".workspace/deploy-vision-prompt" ".workspace/workstreams/deploy/deploy-vision-prompt"
do_move "git mv" ".workspace/deploy-vision-settings" ".workspace/workstreams/deploy/deploy-vision-settings"
do_move "git mv" ".workspace/deploy-workerspace" ".workspace/workstreams/deploy/deploy-workerspace"
do_move "git mv" ".workspace/baseline-011" ".workspace/workstreams/baseline-011"
do_move "git mv" ".workspace/dsh-usage-src" ".workspace/workstreams/sources/dsh-usage-src"
do_move "git mv" ".workspace/dsh-vision-adam-src" ".workspace/workstreams/sources/dsh-vision-adam-src"
do_move "git mv" ".workspace/plugin-restore" ".workspace/workstreams/plugin-restore"
do_move "git mv" ".workspace/side-deploy" ".workspace/workstreams/side-deploy"
do_move "git mv" ".workspace/upstream-015-diff" ".workspace/workstreams/upstream-015-diff"
do_move "git mv" ".workspace/tmp-tgz-audit" ".workspace/workstreams/tmp-tgz-audit"
do_move "git mv" ".workspace/research-dsh-workerspace" ".workspace/workstreams/research/research-dsh-workerspace"
do_move "git mv" ".workspace/research" ".workspace/workstreams/research/research"
do_move "git mv" ".workspace/npm-cache" ".workspace/workstreams/npm-cache"

# ── ③ .workspace 未跟踪/已忽略条目（19 条普通 mv）──
do_move "mv" ".workspace/twin-probe" ".workspace/probes/twin"
do_move "mv" ".workspace/vision-test" ".workspace/probes/vision-test"
do_move "mv" ".workspace/backup-batch-20260914-142844" ".workspace/backups/plugins/20260914-142844-batch"
do_move "mv" ".workspace/backup-batch2-20260914-142947" ".workspace/backups/plugins/20260914-142947-batch2"
do_move "mv" ".workspace/backup-btw-20260917-170146" ".workspace/backups/btw/20260917-170146"
do_move "mv" ".workspace/backup-btw-20260917-172915" ".workspace/backups/btw/20260917-172915"
do_move "mv" ".workspace/backup-btw-deploy-20260912-165932" ".workspace/backups/btw/20260912-165932-deploy"
do_move "mv" ".workspace/backup-btw-deploy-20260912-180420-lib" ".workspace/backups/btw/20260912-180420-deploy-lib"
do_move "mv" ".workspace/backup-config" ".workspace/backups/config"
do_move "mv" ".workspace/backup-methodology-20260912-164548" ".workspace/backups/methodology/20260912-164548"
do_move "mv" ".workspace/backup-methodology-20260912-164933" ".workspace/backups/methodology/20260912-164933"
do_move "mv" ".workspace/backup-patched" ".workspace/backups/patched"
do_move "mv" ".workspace/backup-plugins" ".workspace/backups/plugins/plugins"
do_move "mv" ".workspace/backup-subagent-model-20260917-165928" ".workspace/backups/subagent-model/20260917-165928"
do_move "mv" ".workspace/backup-usage-heatmap-20260914-094352" ".workspace/backups/usage-heatmap/20260914-094352"
do_move "mv" ".workspace/backup-ws-20260914-145449" ".workspace/backups/workspace/20260914-145449"
do_move "mv" ".workspace/repos" ".workspace/workstreams/research/repos"
do_move "mv" ".workspace/research-luxweft-doc" ".workspace/workstreams/research/research-luxweft-doc"
do_move "mv" ".workspace/tmp-ppt-research" ".workspace/workstreams/research/tmp-ppt-research"

# ── 原地保留（6 条，不搬移）──
# keep: README.md
# keep: FEATURE-MAP.md
# keep: DOC-STYLE.md
# keep: .workspace/settings-lag
# keep: .workspace/lag-fix
# keep: .workspace/docs-reorg

echo "===== 小计: OK=$ok SKIP=$skip FAIL=$fail ====="
[ "$fail" -eq 0 ] || exit 1
