import { DatabaseSync } from "node:sqlite";
const db = new DatabaseSync(process.env.HOME + "/.dsh/storages/usage/usage.db", { readOnly: true });
db.exec("PRAGMA temp_store = MEMORY");
const t = (l, fn) => { const a = performance.now(); const r = fn(); console.log(`${l.padEnd(38)} ${(performance.now() - a).toFixed(1).padStart(8)} ms`); return r; };
const q = (s, ...v) => db.prepare(s).all(...v);
const DAY = "strftime('%Y-%m-%d', ts / 1000, 'unixepoch', 'localtime')";
const HOUR = "strftime('%Y-%m-%d %H', ts / 1000, 'unixepoch', 'localtime')";
const from = Date.now() - 30 * 86400_000;
console.log("=== per 30s poll cycle (loadAll, exactly as client.js:825-837) ===");
t("summary (30d window)", () => q(`SELECT COUNT(*) AS requests, SUM(input_tokens) AS i, SUM(output_tokens) AS o, SUM(cache_read_tokens) AS cr, SUM(cache_write_tokens) AS cw, COUNT(DISTINCT session_id) AS sessions FROM usage_events WHERE ts >= ?`, from));
t("timeseries day (30d window)", () => q(`SELECT ${DAY} AS day, COUNT(*) FROM usage_events WHERE ts >= ? GROUP BY day ORDER BY day`, from));
t("timeseries HOUR (trend window)", () => q(`SELECT ${HOUR} AS day, COUNT(*) FROM usage_events WHERE ts >= ? GROUP BY day ORDER BY day`, Date.now() - 86400_000));
t("heatmap (year, DAY_SQL BETWEEN)", () => q(`SELECT ${DAY} AS day, COUNT(*) FROM usage_events WHERE ${DAY} BETWEEN ? AND ? GROUP BY day ORDER BY day`, "2026-01-01", "2026-12-31"));
t("byModel (30d)", () => q(`SELECT COALESCE(model,'(unknown)'), COUNT(*) FROM usage_events WHERE ts >= ? GROUP BY 1 ORDER BY 2 DESC`, from));
t("byProject (30d)", () => q(`SELECT COALESCE(project,'(unknown)'), COUNT(*) FROM usage_events WHERE ts >= ? GROUP BY 1 ORDER BY 2 DESC`, from));
t("byDay (30d)", () => q(`SELECT ${DAY} AS day, COUNT(*) FROM usage_events WHERE ts >= ? GROUP BY day ORDER BY day`, from));
t("status eventsDsh COUNT(*)", () => q(`SELECT COUNT(*) AS n FROM usage_events WHERE data_source = 'dsh'`));
t("status eventsCc COUNT(*)", () => q(`SELECT COUNT(*) AS n FROM usage_events WHERE data_source = 'cc'`));
const total = (() => { const a = performance.now();
  q(`SELECT COUNT(*) FROM usage_events WHERE ts >= ?`, from);
  q(`SELECT ${DAY} FROM usage_events WHERE ts >= ? GROUP BY 1 ORDER BY 1`, from);
  q(`SELECT ${HOUR} FROM usage_events WHERE ts >= ? GROUP BY 1 ORDER BY 1`, Date.now() - 86400_000);
  q(`SELECT ${DAY} FROM usage_events WHERE ${DAY} BETWEEN ? AND ? GROUP BY 1 ORDER BY 1`, "2026-01-01", "2026-12-31");
  q(`SELECT model FROM usage_events WHERE ts >= ? GROUP BY 1`, from);
  q(`SELECT project FROM usage_events WHERE ts >= ? GROUP BY 1`, from);
  q(`SELECT ${DAY} FROM usage_events WHERE ts >= ? GROUP BY 1`, from);
  return performance.now() - a; })();
console.log(`${"ONE 7-QUERY POLL CYCLE (main thread)".padEnd(38)} ${total.toFixed(1).padStart(8)} ms`);
console.log("=== full-table-scan variants (no date window) ===");
t("heatmap no window", () => q(`SELECT ${DAY} FROM usage_events GROUP BY 1`));
db.close();
